[source](https://discord.com/channels/460871933748183040/1284455151209418783) by [Paulitos](https://github.com/Paulitos)

# Problem 
`consumer_service` errors connecting to RabbitMQ

## Solution
The Python script did not specify RabbitMQ's credentials